[package]
name = "compression_golf"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bytes = "1"
chrono = "0.4"
zstd = "0.13"
pco = "1.0.0"
